### ISSUE TITLE
Slime Fletching nicht herstell bar

### ISSUE THREAD

**Issue by Alheimerjung** [BakermanLP/ModpackProjectRETv7#186]
![2014-12-22_21 08 38](https://cloud.githubusercontent.com/assets/8871046/5530352/f9759e22-8a1e-11e4-9066-c0b272e61155.png)

**Comment by BakermanLP** [comment]
Ja ja, wenn ich es nicht vergessen hätte diesmal. Deswegen schliesse ich das manuell.
